/**
 * Email transport — Resend.
 *
 * Migrated from nodemailer + Gmail SMTP on 2026-06 (see ndm conversation
 * + the prospect-pool work for context). The 8 named functions below
 * preserve their original signatures so consumer routes
 * (app/api/send-*-email/route.ts + convex/domains.ts callers) need no
 * changes. The only real swap is what happens inside `sendEmail`.
 *
 * Env vars:
 *   - RESEND_API_KEY     — required. Format `re_xxxxxxxxxxxx…`.
 *   - RESEND_FROM_EMAIL  — optional. Default falls back to
 *     `Tendso <onboarding@resend.dev>` (Resend's test sender,
 *     works without DNS verification). Swap to a verified domain
 *     address by setting this env var only — no code redeploy needed.
 *   - RESEND_REPLY_TO    — optional. When set, every outgoing email
 *     gets a reply_to header so customer replies land in this inbox
 *     instead of bouncing off the unverified onboarding@ sender.
 *
 * Why we keep nodemailer in package.json for now: rollback insurance.
 * If Resend has an outage in the first week we can revert this single
 * file and the old SMTP path comes back. Remove nodemailer +
 * @types/nodemailer + GMAIL_USER/GMAIL_APP_PASSWORD in a follow-up
 * cleanup PR after Resend is verified in prod.
 */
import { Resend } from 'resend';
import {
    getApprovalEmailHtml,
    getPaymentConfirmationEmailHtml,
    getPaymentLinkEmailHtml,
    getPaymentFollowUpEmailHtml,
    getDomainLiveEmailHtml,
    getDomainSetupInProgressEmailHtml,
    getDomainRenewalReminderEmailHtml,
    getWithdrawalStatusEmailHtml,
} from './templates';

// ── Transport ─────────────────────────────────────────────────────────

const DEFAULT_FROM = 'Tendso <onboarding@resend.dev>';

// Lazy-init the Resend client so unit tests / build-time imports don't
// require the env var to exist. The client is cheap to construct;
// memoizing prevents repeated reads of process.env at hot paths.
let _resend: Resend | null = null;
function getClient(): Resend {
    if (_resend) return _resend;
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
        throw new Error(
            'RESEND_API_KEY is not set on this deployment. ' +
                'Add it to .env.local (dev) or Vercel env (prod) and redeploy.',
        );
    }
    _resend = new Resend(apiKey);
    return _resend;
}

interface SendArgs {
    to: string;
    subject: string;
    html: string;
}

/**
 * Single source of truth for outbound mail. Every named function below
 * funnels through here so the from / reply_to / error-handling logic is
 * defined exactly once.
 *
 * On success: returns `{ success: true, messageId }` matching the prior
 * nodemailer shape so consumer routes don't notice the swap.
 * On failure: throws so the caller's try/catch + API-route 500 path
 * keeps working the same way it did with SMTP errors.
 */
async function sendEmail(args: SendArgs): Promise<{ success: true; messageId: string }> {
    const from = process.env.RESEND_FROM_EMAIL || DEFAULT_FROM;
    const replyTo = process.env.RESEND_REPLY_TO;
    const client = getClient();

    const result = await client.emails.send({
        from,
        to: args.to,
        subject: args.subject,
        html: args.html,
        ...(replyTo ? { replyTo } : {}),
    });

    if (result.error) {
        // Resend's error object has { message, name, statusCode? }.
        // Throw a plain Error so the consumer's existing catch block
        // gets the same shape it did with nodemailer's SMTPError.
        throw new Error(
            `Resend send failed: ${result.error.message ?? result.error.name ?? 'unknown error'}`,
        );
    }

    return { success: true, messageId: result.data?.id ?? 'unknown' };
}

// ── Named functions (signatures unchanged from nodemailer version) ────

interface ApprovalEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    websiteUrl: string;
    amount: number;
    submissionId: string;
    paymentReference?: string; // ND-XXXX-YYYY format, generated by paymentReferences.generate
}

export async function sendApprovalEmail(data: ApprovalEmailData) {
    try {
        const html = getApprovalEmailHtml({
            businessName: data.businessName,
            businessOwnerName: data.businessOwnerName,
            websiteUrl: data.websiteUrl,
            amount: data.amount,
            submissionId: data.submissionId,
            paymentReference: data.paymentReference,
        });
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject: `🎉 Your Website is Ready — ${data.businessName}`,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendApprovalEmail:', error);
        throw error;
    }
}

interface PaymentLinkEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    amount: number;
    paymentLink: string;
    referenceCode: string;
    platformEmail?: string;
    customDomain?: string; // If set, template shows breakdown (website ₱1,000 + domain ₱500)
}

export async function sendPaymentLinkEmail(data: PaymentLinkEmailData) {
    try {
        const html = getPaymentLinkEmailHtml({
            businessName: data.businessName,
            businessOwnerName: data.businessOwnerName,
            amount: data.amount,
            paymentLink: data.paymentLink,
            referenceCode: data.referenceCode,
            platformEmail: data.platformEmail,
            customDomain: data.customDomain,
        });
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject: `💰 Complete Payment to Go Live — ${data.businessName} Website`,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendPaymentLinkEmail:', error);
        throw error;
    }
}

interface PaymentFollowUpEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    amount: number;
    websiteUrl?: string;
    referenceCode?: string;
    hoursLeft?: number;
    /** true = admin manually triggered; false = automated 24h-before-unpublish cron */
    isManual?: boolean;
}

export async function sendPaymentFollowUpEmail(data: PaymentFollowUpEmailData) {
    try {
        const html = getPaymentFollowUpEmailHtml({
            businessName: data.businessName,
            businessOwnerName: data.businessOwnerName,
            websiteUrl: data.websiteUrl,
            amount: data.amount,
            referenceCode: data.referenceCode,
            hoursLeft: data.hoursLeft,
            isManual: data.isManual,
        });
        const subject = data.isManual
            ? `Following up on your website — ${data.businessName}`
            : `⏰ Last day — ${data.businessName} website goes offline tomorrow`;
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendPaymentFollowUpEmail:', error);
        throw error;
    }
}

interface PaymentConfirmationEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    websiteUrl: string;
    amount: number;
}

export async function sendPaymentConfirmationEmail(data: PaymentConfirmationEmailData) {
    try {
        const html = getPaymentConfirmationEmailHtml({
            businessName: data.businessName,
            businessOwnerName: data.businessOwnerName,
            websiteUrl: data.websiteUrl,
            amount: data.amount,
        });
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject: `Payment Confirmed — ${data.businessName} is Now Live!`,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendPaymentConfirmationEmail:', error);
        throw error;
    }
}

interface DomainLiveEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    customDomain: string;
    expiresAt: number;
}

export async function sendDomainLiveEmail(data: DomainLiveEmailData) {
    try {
        const html = getDomainLiveEmailHtml(data);
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject: `🎉 ${data.customDomain} is Live — Your ${data.businessName} Website is Online!`,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendDomainLiveEmail:', error);
        throw error;
    }
}

interface DomainSetupInProgressEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    customDomain: string;
}

export async function sendDomainSetupInProgressEmail(data: DomainSetupInProgressEmailData) {
    try {
        const html = getDomainSetupInProgressEmailHtml(data);
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject: `⏳ Setting up ${data.customDomain} — ${data.businessName}`,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendDomainSetupInProgressEmail:', error);
        throw error;
    }
}

interface DomainRenewalReminderEmailData {
    businessName: string;
    businessOwnerName: string;
    businessOwnerEmail: string;
    customDomain: string;
    expiresAt: number;
}

export async function sendDomainRenewalReminderEmail(data: DomainRenewalReminderEmailData) {
    try {
        const html = getDomainRenewalReminderEmailHtml(data);
        return await sendEmail({
            to: data.businessOwnerEmail,
            subject: `⏰ Renew ${data.customDomain} — ${data.businessName}`,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendDomainRenewalReminderEmail:', error);
        throw error;
    }
}

interface WithdrawalStatusEmailData {
    creatorName: string;
    creatorEmail: string;
    amount: number;
    statusLabel: string; // e.g. "Verifying your details"
    statusDescription: string; // longer human-readable explanation
    isFinal: boolean; // true = completed/failed, false = still in progress
    referenceCode?: string; // Wise transfer ID
    submittedAt: number;
}

export async function sendWithdrawalStatusEmail(data: WithdrawalStatusEmailData) {
    try {
        const html = getWithdrawalStatusEmailHtml(data);
        const subject = data.isFinal
            ? `✅ Withdrawal of ₱${data.amount} — ${data.statusLabel}`
            : `⏳ Withdrawal Update: ₱${data.amount} — ${data.statusLabel}`;
        return await sendEmail({
            to: data.creatorEmail,
            subject,
            html,
        });
    } catch (error: any) {
        console.error('Error in sendWithdrawalStatusEmail:', error);
        throw error;
    }
}

// ── Re-exports used by getApprovalEmailHtml callers (preview etc.) ────
// Templates module is the canonical source; re-exporting here is a no-op
// but documents the public surface for grep-discoverability.
export {
    getApprovalEmailHtml,
    getPaymentConfirmationEmailHtml,
    getPaymentLinkEmailHtml,
    getPaymentFollowUpEmailHtml,
    getDomainLiveEmailHtml,
    getDomainSetupInProgressEmailHtml,
    getDomainRenewalReminderEmailHtml,
    getWithdrawalStatusEmailHtml,
};
