/**
 * WHAT EACH TEMPLATE CALLS ITS SECTIONS.
 *
 * "SERVICES", "WHY-US", "CTA-BAND" are OUR vocabulary. They are what the
 * visibility keys are named after and they are meaningless to the person
 * looking at the page. Kubo Stays does not have a "services section" — it has
 * The rooms. It does not have "WHY-US" — it has The house. An admin deciding
 * whether to switch something off needs the name that is on the page and a line
 * saying what disappears with it.
 *
 * MEMBERSHIP AND ORDER DO NOT LIVE HERE. They are generated from the wrappers
 * into templateSectionOrder.generated.ts, so this file cannot make a panel offer
 * a section a template does not render, or hide one it does — the worst a wrong
 * entry here can do is mislabel something. scripts/check-template-blocks.mjs
 * fails on any label keyed to a block its template never renders.
 *
 * A template with no entry, or a block with no entry inside one, falls back to
 * DEFAULT_SECTION_LABELS. A block whose name matches the default exactly has no
 * entry here on purpose — silence means "the generic word is the right word".
 * Inventing flavour that is not on the page is worse than being plain.
 */

export interface SectionLabel {
    /** 1–3 words, sentence case, as the section reads on the page. */
    label: string;
    /** At most ~9 words. What is inside it, in concrete nouns. */
    blurb: string;
}

/** Used whenever a template has nothing more specific to say. */
export const DEFAULT_SECTION_LABELS: Record<string, SectionLabel> = {
    "HERO":           { label: "Hero", blurb: "Opening headline, intro line, buttons and lead photo" },
    "MARQUEE":        { label: "Marquee", blurb: "The scrolling band of short phrases" },
    "TRUST":          { label: "Trust strip", blurb: "Short proof figures under the hero" },
    "ABOUT":          { label: "About", blurb: "The owner's story, portrait and signature" },
    "SERVICES":       { label: "Services", blurb: "What the business sells, as cards" },
    "WHY-US":         { label: "Why us", blurb: "Reasons to choose this business" },
    "HOW-IT-WORKS":   { label: "How it works", blurb: "The numbered steps to getting started" },
    "TESTIMONIALS":   { label: "Reviews", blurb: "Customer quotes and who said them" },
    "GALLERY":        { label: "Gallery", blurb: "The photo grid" },
    "FAQ":            { label: "FAQ", blurb: "Questions and answers" },
    "SERVICE-AREA":   { label: "Service area", blurb: "The places this business covers" },
    "CREDENTIALS":    { label: "Credentials", blurb: "Licences, memberships and promises" },
    "LOCATION":       { label: "Location", blurb: "Map, address, hours and directions" },
    "CTA-BAND":       { label: "Closing band", blurb: "The last call to action before the footer" },
    "FOOTER":         { label: "Footer", blurb: "Contact details, links and the message pill" },
};

/**
 * Per-template names, keyed by template code then by block name. Read off each
 * template's own wrapper and hand-authored preview — the eyebrow and headline it
 * actually prints over that section.
 */
export const TEMPLATE_SECTION_LABELS: Record<string, Record<string, SectionLabel>> = {
    "autoshop:AF": {
        "HERO":         { label: "Hero", blurb: "Job-sheet tag, headline, two buttons, tilted bay photo" },
        "TRUST":        { label: "Trust bar", blurb: "Ink strip of years, rating, hours, certification notes" },
        "ABOUT":        { label: "Shop history", blurb: "Shop-history paragraphs on a sheet beside bay photo" },
        "SERVICES":     { label: "Work orders", blurb: "Hazard-bordered job-order cards, numbered, with descriptions" },
        "WHY-US":       { label: "Why us", blurb: "Stacked rows: photo policy, estimates, certification, records" },
        "HOW-IT-WORKS": { label: "Procedure", blurb: "Numbered job sheets from call to release" },
        "TESTIMONIALS": { label: "Customer log", blurb: "Quote sheets with customer name and town" },
        "GALLERY":      { label: "Shop floor", blurb: "Steel plates of bay photos with hazard captions" },
        "FAQ":          { label: "Straight answers", blurb: "Accordion of shop questions and answers" },
        "SERVICE-AREA": { label: "Mobile service area", blurb: "Hazard band listing the towns covered" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Thin row of permits, registrations and certifications" },
        "LOCATION":     { label: "Location", blurb: "Map plate, address, phone, weekly hours, directions" },
        "CTA-BAND":     { label: "Closing band", blurb: "Ink band, hazard headline, call and message buttons" },
    },
    "autoshop:AP": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, buttons, bay plate, tacho panel" },
        "TRUST":        { label: "Trust bar", blurb: "Four dark cells: certification, rating, bays, warranty" },
        "ABOUT":        { label: "The shop", blurb: "Shop-story paragraphs beside the frontage photo plate" },
        "SERVICES":     { label: "What we handle", blurb: "SVC-numbered cards with titles, descriptions and tags" },
        "WHY-US":       { label: "Why us", blurb: "Numbered cells: diagnosis, quotes, warranty, one-stop" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps from symptoms to handover" },
        "TESTIMONIALS": { label: "Driver reviews", blurb: "Driver quotes with names and home towns" },
        "GALLERY":      { label: "In the bay", blurb: "Captioned, tagged workshop and detailing bay photos" },
        "FAQ":          { label: "Questions", blurb: "Two-column accordion of shop questions and answers" },
        "SERVICE-AREA": { label: "Drivers come from", blurb: "Amber kicker over tags of nearby towns" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Badge tiles: certified techs, DTI, permit, insurance" },
        "LOCATION":     { label: "Find the shop", blurb: "Shop name, address, phone, hours and map" },
        "CTA-BAND":     { label: "Get a quote", blurb: "Amber closing band with message and call buttons" },
    },
    "autoshop:P": {
        "HERO":         { label: "Hero", blurb: "Headline, intro, two buttons, rating line, photo, badge" },
        "TRUST":        { label: "Trust strip", blurb: "Dark band of four big figures and labels" },
        "ABOUT":        { label: "About", blurb: "Lead paragraph, body copy and the bordered stat rail" },
        "SERVICES":     { label: "What we fix", blurb: "Numbered service rows with descriptions and Book links" },
        "WHY-US":       { label: "Why drivers stay", blurb: "Panel of ruled cells, each icon, title and copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered step cells in one bordered three-across row" },
        "TESTIMONIALS": { label: "What they say", blurb: "Stacked review rows with source, stars, quote and name" },
        "GALLERY":      { label: "In the bays", blurb: "Bento photo grid, captions appear on hover" },
        "FAQ":          { label: "Good to know", blurb: "Two columns of expandable question-and-answer rows" },
        "SERVICE-AREA": { label: "Neighborhoods we serve", blurb: "Dark band of outlined place tags" },
        "CREDENTIALS":  { label: "Licensed & certified", blurb: "Bordered badge cards with a mark, name and note" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, email, hours, buttons and the map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Orange band with headline, line of copy, two buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, social row, link columns and bottom rule" },
    },
    "autoshop:Q": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo, kicker, headline, intro, buttons and rating line" },
        "TRUST":        { label: "Trust strip", blurb: "Dark band of four big figures and labels" },
        "ABOUT":        { label: "Our story", blurb: "Lead paragraph, body copy and the bordered stat rail" },
        "SERVICES":     { label: "Services", blurb: "Numbered service rows with descriptions and Book links" },
        "WHY-US":       { label: "The difference", blurb: "Panel of ruled cells, each icon, title and copy" },
        "HOW-IT-WORKS": { label: "The process", blurb: "Numbered step cells in one bordered three-across row" },
        "TESTIMONIALS": { label: "In their words", blurb: "Stacked review rows with source, stars, quote and name" },
        "GALLERY":      { label: "Inside the shop", blurb: "Bento photo grid, captions appear on hover" },
        "FAQ":          { label: "Good to know", blurb: "Two columns of expandable question-and-answer rows" },
        "SERVICE-AREA": { label: "Service area", blurb: "Dark band of outlined place tags" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Bordered badge cards with a mark, name and note" },
        "LOCATION":     { label: "Visit the shop", blurb: "Address, phone, email, hours, buttons and the map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Brass band with headline, line of copy, two buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, social row, link columns and bottom rule" },
    },
    "autoshop:R": {
        "HERO":         { label: "Hero", blurb: "Centred headline, buttons, rating and photo stage with badge" },
        "TRUST":        { label: "Trust strip", blurb: "Dark band of four big figures and labels" },
        "ABOUT":        { label: "About", blurb: "Lead paragraph, body copy and the bordered stat rail" },
        "SERVICES":     { label: "Services", blurb: "Numbered service rows with descriptions and Book links" },
        "WHY-US":       { label: "Why us", blurb: "Panel of ruled cells, each icon, title and copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered step cells in one bordered three-across row" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Stacked review rows with source, stars, quote and name" },
        "GALLERY":      { label: "Gallery", blurb: "Bento photo grid, captions appear on hover" },
        "FAQ":          { label: "Questions, answered", blurb: "Two columns of expandable question-and-answer rows" },
        "SERVICE-AREA": { label: "Neighborhoods we serve", blurb: "Dark band of outlined place tags" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Bordered badge cards with a mark, name and note" },
        "LOCATION":     { label: "Visit us", blurb: "Address, phone, email, hours, buttons and the map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Blue band with headline, line of copy, two buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, social row, link columns and bottom rule" },
    },
    "autoshop:S": {
        "HERO":         { label: "Hero", blurb: "Kicker, oversized headline, buttons, rating line and photo strip" },
        "TRUST":        { label: "Trust strip", blurb: "Dark band of four big figures and labels" },
        "ABOUT":        { label: "The shop", blurb: "Lead paragraph, body copy and the bordered stat rail" },
        "SERVICES":     { label: "The work", blurb: "Numbered service rows with descriptions and Book links" },
        "WHY-US":       { label: "Why us", blurb: "Panel of ruled cells, each icon, title and copy" },
        "HOW-IT-WORKS": { label: "How it runs", blurb: "Numbered step cells in one bordered three-across row" },
        "TESTIMONIALS": { label: "Word on the street", blurb: "Stacked review rows with source, stars, quote and name" },
        "GALLERY":      { label: "In the bays", blurb: "Bento photo grid, captions appear on hover" },
        "FAQ":          { label: "Straight answers", blurb: "Two columns of expandable question-and-answer rows" },
        "SERVICE-AREA": { label: "Where we roll", blurb: "Dark band of outlined place tags" },
        "CREDENTIALS":  { label: "Legit & certified", blurb: "Bordered badge cards with a mark, name and note" },
        "LOCATION":     { label: "Roll on by", blurb: "Address, phone, email, hours, buttons and the dark map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Lime band with headline, line of copy, two buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, social row, link columns and bottom rule" },
    },
    "autoshop:T": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, buttons, shop photo, since-seal and rating" },
        "TRUST":        { label: "Trust bar", blurb: "Stat tiles: years, vehicles serviced, warranty, rating" },
        "ABOUT":        { label: "Our story", blurb: "Shop-story paragraphs, a photo and stat pairs" },
        "SERVICES":     { label: "Our services", blurb: "Numbered service rows with one-line descriptions and prices" },
        "WHY-US":       { label: "The difference", blurb: "Icon cells: quotes, diagnostics, loaners, warranty, certification" },
        "HOW-IT-WORKS": { label: "The process", blurb: "Numbered framed steps from booking to drive-away" },
        "TESTIMONIALS": { label: "Kind words", blurb: "Stacked quotes with source label, stars, name, context" },
        "GALLERY":      { label: "The gallery", blurb: "Asymmetric shop-photo grid with index numbers and captions" },
        "FAQ":          { label: "Questions", blurb: "Accordion of shop questions and answers" },
        "SERVICE-AREA": { label: "Service area", blurb: "Tag list of neighbourhoods the shop serves" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Bordered badges naming certifications, licences and ratings" },
        "LOCATION":     { label: "Visit the shop", blurb: "Address, phone, email, hours, map and buttons" },
        "CTA-BAND":     { label: "Closing band", blurb: "Oxblood band, headline, book and call buttons" },
    },
    "barbershop:BP": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo in a hairline frame, didone headline, buttons and a three-cell USP strip" },
        "TRUST":        { label: "Trust strip", blurb: "Brass bar: years, rating, licence, days open" },
        "ABOUT":        { label: "The shop", blurb: "Shop story paragraphs, pull-quote, signature and photo stamp" },
        "SERVICES":     { label: "Services", blurb: "Numbered service cards with description and optional note tag" },
        "WHY-US":       { label: "The difference", blurb: "Dark band, four numbered reasons with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three-step timeline from booking to finished cut" },
        "TESTIMONIALS": { label: "The regulars", blurb: "Featured customer quote plus smaller quote cards" },
        "GALLERY":      { label: "The work", blurb: "Dark band of five photo tiles with captions" },
        "FAQ":          { label: "FAQ", blurb: "Heading column beside expandable question and answer list" },
        "SERVICE-AREA": { label: "Service area", blurb: "Grid of neighbourhoods and towns you cover" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dark band: licence, insurance, inspection badges with icons" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, hours, map and directions button" },
        "MARQUEE":      { label: "Moving marquee", blurb: "Giant scrolling band of service words" },
        "CTA-BAND":     { label: "CTA band", blurb: "Brass closing band: headline, call and booking buttons" },
    },
    "barbershop:F": {
        "HERO":         { label: "Hero", blurb: "Headline, buttons, framed photo, seal, rating, word marquee" },
        "TRUST":        { label: "Trust strip", blurb: "Brass bar: years, rating, licence, days open" },
        "ABOUT":        { label: "The shop", blurb: "Shop story paragraphs, pull-quote, signature and photo stamp" },
        "SERVICES":     { label: "Services", blurb: "Numbered service cards with description and optional note tag" },
        "WHY-US":       { label: "The difference", blurb: "Dark band, four numbered reasons with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three-step timeline from booking to finished cut" },
        "TESTIMONIALS": { label: "The regulars", blurb: "Featured customer quote plus smaller quote cards" },
        "GALLERY":      { label: "The work", blurb: "Dark band of five photo tiles with captions" },
        "FAQ":          { label: "FAQ", blurb: "Heading column beside expandable question and answer list" },
        "SERVICE-AREA": { label: "Service area", blurb: "Grid of neighbourhoods and towns you cover" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dark band: licence, insurance, inspection badges with icons" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, hours, map and directions button" },
        "MARQUEE":      { label: "Moving marquee", blurb: "Giant scrolling band of service words" },
        "CTA-BAND":     { label: "CTA band", blurb: "Brass closing band: headline, call and booking buttons" },
    },
    "barbershop:G": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo, rising headline, buttons and rating row" },
        "TRUST":        { label: "Trust strip", blurb: "Brass bar: years, rating, licence, days open" },
        "ABOUT":        { label: "The shop", blurb: "Shop story paragraphs, pull-quote, signature and photo stamp" },
        "SERVICES":     { label: "Services", blurb: "Numbered service cards with description and optional note tag" },
        "WHY-US":       { label: "The difference", blurb: "Dark band, four numbered reasons with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three-step timeline from booking to finished cut" },
        "TESTIMONIALS": { label: "The regulars", blurb: "Featured customer quote plus smaller quote cards" },
        "GALLERY":      { label: "The work", blurb: "Dark band of five photo tiles with captions" },
        "FAQ":          { label: "FAQ", blurb: "Heading column beside expandable question and answer list" },
        "SERVICE-AREA": { label: "Service area", blurb: "Grid of neighbourhoods and towns you cover" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dark band: licence, insurance, inspection badges with icons" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, hours, map and directions button" },
        "MARQUEE":      { label: "Moving marquee", blurb: "Giant scrolling band of service words" },
        "CTA-BAND":     { label: "CTA band", blurb: "Brass closing band: headline, call and booking buttons" },
    },
    "barbershop:H": {
        "HERO":         { label: "Hero", blurb: "Ghost word, headline, buttons, photo card, badge, marquee" },
        "TRUST":        { label: "Trust strip", blurb: "Brass bar: years, rating, licence, days open" },
        "ABOUT":        { label: "The shop", blurb: "Shop story paragraphs, pull-quote, signature and photo stamp" },
        "SERVICES":     { label: "Services", blurb: "Numbered service cards with description and optional note tag" },
        "WHY-US":       { label: "The difference", blurb: "Dark band, four numbered reasons with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three-step timeline from booking to finished cut" },
        "TESTIMONIALS": { label: "The regulars", blurb: "Featured customer quote plus smaller quote cards" },
        "GALLERY":      { label: "The work", blurb: "Dark band of five photo tiles with captions" },
        "FAQ":          { label: "FAQ", blurb: "Heading column beside expandable question and answer list" },
        "SERVICE-AREA": { label: "Service area", blurb: "Grid of neighbourhoods and towns you cover" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dark band: licence, insurance, inspection badges with icons" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, hours, map and directions button" },
        "MARQUEE":      { label: "Moving marquee", blurb: "Giant scrolling band of service words" },
        "CTA-BAND":     { label: "CTA band", blurb: "Brass closing band: headline, call and booking buttons" },
    },
    "barbershop:I": {
        "HERO":         { label: "Hero", blurb: "Centred eyebrow, big title, buttons, meta row, photo strip" },
        "TRUST":        { label: "Trust strip", blurb: "Brass bar: years, rating, licence, days open" },
        "ABOUT":        { label: "The shop", blurb: "Shop story paragraphs, pull-quote, signature and photo stamp" },
        "SERVICES":     { label: "Services", blurb: "Numbered service cards with description and optional note tag" },
        "WHY-US":       { label: "The difference", blurb: "Dark band, four numbered reasons with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three-step timeline from booking to finished cut" },
        "TESTIMONIALS": { label: "The regulars", blurb: "Featured customer quote plus smaller quote cards" },
        "GALLERY":      { label: "The work", blurb: "Dark band of five photo tiles with captions" },
        "FAQ":          { label: "FAQ", blurb: "Heading column beside expandable question and answer list" },
        "SERVICE-AREA": { label: "Service area", blurb: "Grid of neighbourhoods and towns you cover" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dark band: licence, insurance, inspection badges with icons" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, hours, map and directions button" },
        "MARQUEE":      { label: "Moving marquee", blurb: "Giant scrolling band of service words" },
        "CTA-BAND":     { label: "CTA band", blurb: "Brass closing band: headline, call and booking buttons" },
    },
    "barbershop:J": {
        "HERO":         { label: "Hero", blurb: "Ghost word, headline, buttons, mini stats, photos, rating, seal" },
        "TRUST":        { label: "Trust strip", blurb: "Brass bar: years, rating, licence, days open" },
        "ABOUT":        { label: "The shop", blurb: "Shop story paragraphs, pull-quote, signature and photo stamp" },
        "SERVICES":     { label: "Services", blurb: "Numbered service cards with description and optional note tag" },
        "WHY-US":       { label: "The difference", blurb: "Dark band, four numbered reasons with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three-step timeline from booking to finished cut" },
        "TESTIMONIALS": { label: "The regulars", blurb: "Featured customer quote plus smaller quote cards" },
        "GALLERY":      { label: "The work", blurb: "Dark band of five photo tiles with captions" },
        "FAQ":          { label: "FAQ", blurb: "Heading column beside expandable question and answer list" },
        "SERVICE-AREA": { label: "Service area", blurb: "Grid of neighbourhoods and towns you cover" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dark band: licence, insurance, inspection badges with icons" },
        "LOCATION":     { label: "Find the shop", blurb: "Address, phone, hours, map and directions button" },
        "MARQUEE":      { label: "Moving marquee", blurb: "Giant scrolling band of service words" },
        "CTA-BAND":     { label: "CTA band", blurb: "Brass closing band: headline, call and booking buttons" },
    },
    "education:AJ": {
        "HERO":         { label: "Hero", blurb: "Headline, intro, two buttons and captioned class photo" },
        "TRUST":        { label: "Trust strip", blurb: "Ink strip: years teaching, Google rating, hours, staff" },
        "ABOUT":        { label: "Our story", blurb: "Story paragraphs, founder photo and diagnostic-first note card" },
        "SERVICES":     { label: "Programs", blurb: "Six highlighted program cards, entrance review to summer bridge" },
        "WHY-US":       { label: "Why us", blurb: "Ticked list of four parent-facing promises" },
        "HOW-IT-WORKS": { label: "How enrollment works", blurb: "Four numbered cards from inquiry to first session" },
        "TESTIMONIALS": { label: "The guestbook", blurb: "Quote cards from parents and past students" },
        "GALLERY":      { label: "Around the center", blurb: "Three tilted, captioned photos of the center" },
        "FAQ":          { label: "Questions answered", blurb: "Expandable questions on enrollment, class size, tutors" },
        "SERVICE-AREA": { label: "Students come from", blurb: "One line listing barangays and online student areas" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Inline row: registration, permit, licensed teachers, policy" },
        "LOCATION":     { label: "Visit us", blurb: "Address, phone, weekly hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Ink band: closing headline, sub line, booking button" },
    },
    "education:AT": {
        "HERO":         { label: "Hero", blurb: "Ruled headline card, lede, two buttons, taped photo" },
        "TRUST":        { label: "Trust row", blurb: "Four proof cells: class size, rating, licences, curriculum" },
        "ABOUT":        { label: "The studio", blurb: "Studio story paragraphs beside a taped tutoring photo" },
        "SERVICES":     { label: "Programs", blurb: "Six tabbed program cards, PROG 01 to 06" },
        "WHY-US":       { label: "Why us", blurb: "Three cells: small classes, confidence, visible progress" },
        "HOW-IT-WORKS": { label: "Getting started", blurb: "Four numbered steps from hello to tracked progress" },
        "TESTIMONIALS": { label: "Kind words", blurb: "Star-rated quotes from parents and students" },
        "GALLERY":      { label: "Inside the studio", blurb: "Six taped, captioned photographs of the studio" },
        "FAQ":          { label: "Questions", blurb: "Two columns of expandable questions for parents" },
        "SERVICE-AREA": { label: "Students come from", blurb: "Chips listing towns and online students served" },
        "CREDENTIALS":  { label: "Qualified and safe", blurb: "Four badge cards: licences, safeguarding, registration, curriculum" },
        "LOCATION":     { label: "Find the studio", blurb: "Studio name, address, phone, hours and map" },
        "CTA-BAND":     { label: "Enrol a student", blurb: "Navy closing band with message and call buttons" },
    },
    "filipino:BB": {
        "HERO":         { label: "Hero", blurb: "Kicker, big headline, store photo, lede and buttons" },
        "TRUST":        { label: "Trust row", blurb: "One-line strip of short store claims" },
        "ABOUT":        { label: "The store", blurb: "Store-history paragraphs and the counter photo" },
        "SERVICES":     { label: "What we carry", blurb: "Numbered rows of goods and counter services" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons the corner window works" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps from window to listahan" },
        "TESTIMONIALS": { label: "From the street", blurb: "Lead pull quote plus smaller neighbour quotes" },
        "GALLERY":      { label: "At the window", blurb: "Captioned photo grid of shelf, counter, stock" },
        "FAQ":          { label: "Good to know", blurb: "Expandable answers plus the phone-number intro column" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "List of barangays and areas served" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail pairs: since, tingi, load, listahan" },
        "LOCATION":     { label: "The corner", blurb: "Address, phone, email, hours rows and map" },
        "CTA-BAND":     { label: "Come by", blurb: "Closing headline, paragraph, message and phone buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, address, index links and colophon" },
    },
    "filipino:BC": {
        "HERO":         { label: "Hero", blurb: "Kicker, big headline, ulam photo, lede and buttons" },
        "TRUST":        { label: "Trust row", blurb: "One-line strip of short kitchen claims" },
        "ABOUT":        { label: "The carinderia", blurb: "Kitchen-history paragraphs and the food photo" },
        "SERVICES":     { label: "What's cooking", blurb: "Numbered rows: ulam, combos, baon, catering trays" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons the tables stay full" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps: look, point, eat, order baon" },
        "TESTIMONIALS": { label: "From the tables", blurb: "Lead pull quote plus smaller diner quotes" },
        "GALLERY":      { label: "On the plate", blurb: "Captioned photo grid of dishes, pots, tables" },
        "FAQ":          { label: "Good to know", blurb: "Expandable answers on turo-turo, unli rice, catering" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "List of districts and areas served" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail pairs: since, fresh, unli rice, trays" },
        "LOCATION":     { label: "The kusina", blurb: "Address, phone, email, hours rows and map" },
        "CTA-BAND":     { label: "Come eat", blurb: "Closing headline, paragraph and two contact buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, address, index links and colophon" },
    },
    "filipino:BD": {
        "HERO":         { label: "Hero", blurb: "Kicker, big headline, bread photo, lede and buttons" },
        "TRUST":        { label: "Trust row", blurb: "One-line strip of short bakery claims" },
        "ABOUT":        { label: "The bakery", blurb: "Three-generation story paragraphs and the baker photo" },
        "SERVICES":     { label: "What we bake", blurb: "Numbered rows: pandesal, ensaymada, wholesale, cakes, coffee" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons the bread still tastes right" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps: walk in, order, wholesale, warm" },
        "TESTIMONIALS": { label: "From the queue", blurb: "Lead pull quote plus smaller customer quotes" },
        "GALLERY":      { label: "From the oven", blurb: "Captioned photo grid of bread, shaping, oven, counter" },
        "FAQ":          { label: "Good to know", blurb: "Expandable answers on hours, orders, keeping bread fresh" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "List of towns and areas served" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail pairs: since, 5AM, shaped here, wholesale" },
        "LOCATION":     { label: "The corner", blurb: "Address, phone, email, hours rows and map" },
        "CTA-BAND":     { label: "Come by", blurb: "Closing headline, paragraph and two contact buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, address, index links and colophon" },
    },
    "filipino:BE": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, one photo, lede and two buttons" },
        "TRUST":        { label: "Trust strip", blurb: "Four short proof lines in one thin strip" },
        "ABOUT":        { label: "The roastery", blurb: "Origin-story paragraphs, pull-quote, signature and one photo" },
        "SERVICES":     { label: "The coffee", blurb: "Numbered rows: beans, grinds, cafe and wholesale" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons: real Liberica, fresh roast, farm-direct" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps from choosing a cup to re-ordering" },
        "TESTIMONIALS": { label: "From the cup", blurb: "Lead customer quote plus smaller quote cards" },
        "GALLERY":      { label: "Cherry to cup", blurb: "Captioned photo grid: cherries, roasting, beans and cups" },
        "FAQ":          { label: "Good to know", blurb: "Accordion questions and answers, plus the phone line" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "Pill list of towns served and shipping reach" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail cells: years, sourcing, batch size" },
        "LOCATION":     { label: "Find us", blurb: "Address, phone, email, hours and the map" },
        "CTA-BAND":     { label: "Order", blurb: "Closing headline, blurb, order button and phone" },
    },
    "filipino:BF": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, grill photo, lede and two buttons" },
        "TRUST":        { label: "Trust strip", blurb: "Four short proof lines in one thin strip" },
        "ABOUT":        { label: "The grill", blurb: "Story paragraphs, pull-quote, signature and one photo" },
        "SERVICES":     { label: "Off the grill", blurb: "Numbered menu rows: manok, liempo, barbecue, trays" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons: overnight marinade, live coals, cheap dinner" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps: order, pick, bag and eat" },
        "TESTIMONIALS": { label: "From the kanto", blurb: "Lead customer quote plus smaller quote cards" },
        "GALLERY":      { label: "At the fire", blurb: "Captioned photo grid of spit, coals and plates" },
        "FAQ":          { label: "Before you order", blurb: "Accordion questions and answers, plus the phone line" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "Pill list of delivery towns around Nueva Ecija" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail cells: years, marinade, coals, trays" },
        "LOCATION":     { label: "The kanto", blurb: "Address, phone, email, hours and the map" },
        "CTA-BAND":     { label: "Order", blurb: "Closing headline, blurb, order button and phone" },
    },
    "filipino:BG": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, shop photo, lede and two buttons" },
        "TRUST":        { label: "Trust strip", blurb: "Four short proof lines in one thin strip" },
        "ABOUT":        { label: "The shop", blurb: "Story paragraphs, pull-quote, signature and one photo" },
        "SERVICES":     { label: "What we fix", blurb: "Numbered rows: patching, vulcanizing, balancing, tires, rescue" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons: open 24 hours, rescue, honest fixes" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps: roll in, assess, fix, go" },
        "TESTIMONIALS": { label: "From the roadside", blurb: "Lead customer quote plus smaller quote cards" },
        "GALLERY":      { label: "In the bay", blurb: "Captioned photo grid of repairs, tools, night shift" },
        "FAQ":          { label: "Good to know", blurb: "Accordion questions and answers, plus the phone line" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "Pill list of towns and highways covered" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail cells: years, hours, rescue, honest fixes" },
        "LOCATION":     { label: "Find us", blurb: "Address, phone, email, hours and the map" },
        "CTA-BAND":     { label: "Call", blurb: "Closing headline, blurb, call button and mobile number" },
    },
    "filipino:BH": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, halo-halo photo, lede and two buttons" },
        "TRUST":        { label: "Trust strip", blurb: "Four short proof lines in one thin strip" },
        "ABOUT":        { label: "The haus", blurb: "Story paragraphs, pull-quote, signature and one photo" },
        "SERVICES":     { label: "The glass", blurb: "Numbered menu rows: halo-halo, con yelo, kakanin" },
        "WHY-US":       { label: "The difference", blurb: "Numbered reasons: house-made, snow-fine ice, generous glasses" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered steps: pick, build, mix, take home" },
        "TESTIMONIALS": { label: "From the spoon", blurb: "Lead customer quote plus smaller quote cards" },
        "GALLERY":      { label: "At the counter", blurb: "Captioned photo grid of glasses, kakanin, counter" },
        "FAQ":          { label: "Good to know", blurb: "Accordion questions and answers, plus the phone line" },
        "SERVICE-AREA": { label: "The neighbourhood", blurb: "Pill list of Pampanga towns plus delivery reach" },
        "CREDENTIALS":  { label: "The essentials", blurb: "Label-and-detail cells: years, in-house, ice, take-home" },
        "LOCATION":     { label: "Find us", blurb: "Address, phone, email, hours and the map" },
        "CTA-BAND":     { label: "Come in", blurb: "Closing headline, blurb, order button and mobile number" },
    },
    "fitness:AI": {
        "HERO":         { label: "Hero", blurb: "Poster headline, sub, trial buttons, halftone floor photo" },
        "TRUST":        { label: "Trust strip", blurb: "Ink band: years, rating, hours, coach pedigree" },
        "ABOUT":        { label: "The club", blurb: "Gym story paragraphs beside a cocked coaching photo" },
        "SERVICES":     { label: "Programs", blurb: "Class cards on the full-width blood-red band" },
        "WHY-US":       { label: "Why we're different", blurb: "Ink-boxed claims: coaching, opt-in sparring, hours, pedigree" },
        "HOW-IT-WORKS": { label: "Your first session", blurb: "Numbered cards: message, gear up, class, decide" },
        "TESTIMONIALS": { label: "From the corner", blurb: "Member quotes on the ink band" },
        "GALLERY":      { label: "The floor", blurb: "Cocked halftone photo tiles with captions" },
        "FAQ":          { label: "Before the bell", blurb: "Accordion of beginner, gear and sparring questions" },
        "SERVICE-AREA": { label: "Members roll in from", blurb: "Blood-red lead-in plus the barangays members travel from" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Star-marked row of registration, permit and certification lines" },
        "LOCATION":     { label: "Find the bell", blurb: "Address, phone, weekly hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Blood-red band with closing line and trial button" },
    },
    "fitness:AR": {
        "HERO":         { label: "Hero", blurb: "Full-screen headline, sub, buttons and the class marquee" },
        "TRUST":        { label: "Training ledger", blurb: "Four counter cells: coaches, weekly classes, rating, days" },
        "ABOUT":        { label: "The gym", blurb: "Gym story paragraphs plus a captioned floor photo" },
        "SERVICES":     { label: "Programs", blurb: "Six numbered program cards, barbell through open gym" },
        "WHY-US":       { label: "Why us", blurb: "Four lettered cells: coaching, beginners, programming, community" },
        "HOW-IT-WORKS": { label: "Start in 4", blurb: "Four numbered steps from message to showing up" },
        "TESTIMONIALS": { label: "Member logs", blurb: "Star-rated member quotes with names and areas" },
        "GALLERY":      { label: "The floor", blurb: "Six numbered, captioned photo plates of the gym" },
        "FAQ":          { label: "Before you start", blurb: "Two columns of expandable questions about starting" },
        "SERVICE-AREA": { label: "Members train from", blurb: "Eyebrow plus chips of areas members travel from" },
        "CREDENTIALS":  { label: "Coached by pros", blurb: "Four badge cards: certifications, first aid, permit, insurance" },
        "LOCATION":     { label: "Find us", blurb: "Gym name, address, phone, hours rows and map" },
        "CTA-BAND":     { label: "Come train", blurb: "Lime closing band: eyebrow, headline, message and call buttons" },
    },
    "foodcraft:AL": {
        "HERO":         { label: "Hero", blurb: "Eyebrow, headline, lede, two buttons, arched loaf photo" },
        "TRUST":        { label: "Trust strip", blurb: "Tagline line plus Google rating and today's hours" },
        "ABOUT":        { label: "Our story", blurb: "Bakery story paragraphs and two arched portrait photos" },
        "SERVICES":     { label: "What we bake", blurb: "Printed cards for breads, cakes, boxes and coffee" },
        "WHY-US":       { label: "Why us", blurb: "Asterisk-marked reasons with bold lead-ins" },
        "HOW-IT-WORKS": { label: "Ordering", blurb: "Numbered cards: message, confirm and bake, pick up" },
        "TESTIMONIALS": { label: "The dawn regulars", blurb: "Printed quote cards with customer names and places" },
        "GALLERY":      { label: "Through the arch", blurb: "Arched photo tiles with captions" },
        "FAQ":          { label: "Before you message", blurb: "Expandable questions on orders, delivery, cakes, freshness" },
        "SERVICE-AREA": { label: "Rider delivery", blurb: "Thin strip listing barangays riders deliver to" },
        "CREDENTIALS":  { label: "Permits", blurb: "Thin strip of registrations and permits" },
        "LOCATION":     { label: "The bakery", blurb: "Address, phone, weekly hours, directions button and map" },
        "CTA-BAND":     { label: "Call to action", blurb: "Terracotta band with closing line and Messenger button" },
        "FOOTER":       { label: "Footer", blurb: "Bakery name, blurb, address, phone and link columns" },
    },
    "generic:A": {
        "HERO":         { label: "Hero", blurb: "Background photo, kicker, headline, two buttons and meta lines" },
        "MARQUEE":      { label: "Scrolling band", blurb: "One scrolling line of text under the hero" },
        "TRUST":        { label: "Trust numbers", blurb: "Four gold numbers with labels on the dark band" },
        "ABOUT":        { label: "Our story", blurb: "Two-column story copy with a signed sign-off line" },
        "SERVICES":     { label: "What we do", blurb: "Numbered rows of offerings with descriptions and notes" },
        "WHY-US":       { label: "Why us", blurb: "Four icon cards giving reasons to choose you" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three big-numeral steps with titles and copy" },
        "TESTIMONIALS": { label: "In their words", blurb: "Big pull quote, three review cards, source line" },
        "GALLERY":      { label: "Our work", blurb: "Five-tile photo grid with hover captions" },
        "FAQ":          { label: "Good to know", blurb: "Accordion of questions with expandable answers" },
        "SERVICE-AREA": { label: "Service area", blurb: "Area chips plus the credentials list beside them" },
        "LOCATION":     { label: "Come by", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Gold band with headline, contact line and button" },
    },
    "generic:B": {
        "HERO":         { label: "Hero", blurb: "Backdrop photo, headline, buttons and scrolling image strip" },
        "MARQUEE":      { label: "Scrolling band", blurb: "Scrolling word band beneath the hero" },
        "TRUST":        { label: "Trust numbers", blurb: "Centred row of stat numbers with dot separators" },
        "ABOUT":        { label: "Our story", blurb: "Arched photo with tag bubble, paragraphs and sign-off" },
        "SERVICES":     { label: "What we offer", blurb: "Alternating photo rows with title, text and meta" },
        "WHY-US":       { label: "Why us", blurb: "Three-column icon cards giving reasons to choose you" },
        "HOW-IT-WORKS": { label: "How to begin", blurb: "Vertical numbered timeline of steps with copy" },
        "TESTIMONIALS": { label: "In their words", blurb: "Quote cards in two columns and source line" },
        "GALLERY":      { label: "Our work", blurb: "Six-tile photo grid with hover captions" },
        "FAQ":          { label: "Good to know", blurb: "Accordion of questions with expandable answers" },
        "SERVICE-AREA": { label: "Who we welcome", blurb: "Area chips plus credential pills beside them" },
        "LOCATION":     { label: "Come by", blurb: "Map, address, phone, hours and directions button" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Teal band with headline, contact line and button" },
    },
    "generic:C": {
        "HERO":         { label: "Hero", blurb: "Background photo, kicker, headline, two buttons and meta lines" },
        "MARQUEE":      { label: "Scrolling band", blurb: "Scrolling line of service words under the hero" },
        "TRUST":        { label: "Trust numbers", blurb: "Four bordered stat blocks with numbers and labels" },
        "ABOUT":        { label: "Who we are", blurb: "Story copy, mini stat row and framed photo" },
        "SERVICES":     { label: "What we do", blurb: "Menu-board rows: number, service name, short description" },
        "WHY-US":       { label: "Why us", blurb: "Four icon cards giving reasons to hire you" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three numbered step cards with titles and copy" },
        "TESTIMONIALS": { label: "Word on the street", blurb: "Three review cards and the source line" },
        "GALLERY":      { label: "Recent work", blurb: "Five-tile project photo grid with hover captions" },
        "FAQ":          { label: "Questions", blurb: "Accordion of questions with expandable answers" },
        "SERVICE-AREA": { label: "Where we work", blurb: "Two-column area checklist plus credential badges beside" },
        "LOCATION":     { label: "Find / call us", blurb: "Map with address, phone, hours and call button" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Forest band with headline, contact line and button" },
    },
    "generic:D": {
        "HERO":         { label: "Hero", blurb: "Headline, buttons and the editable terminal status panel" },
        "MARQUEE":      { label: "Scrolling band", blurb: "Scrolling line of service words under the hero" },
        "TRUST":        { label: "Trust numbers", blurb: "Four key/value stat cells in one bordered strip" },
        "ABOUT":        { label: "About us", blurb: "Photo with code tag, paragraphs and a note" },
        "SERVICES":     { label: "Services", blurb: "Bento grid of tagged service cards with icons" },
        "WHY-US":       { label: "Why us", blurb: "Tick-marked reason rows in two columns" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Stacked step rows tagged step_01 with title and copy" },
        "TESTIMONIALS": { label: "Client reviews", blurb: "One featured quote, smaller quote cards, source line" },
        "GALLERY":      { label: "Our work", blurb: "Four-tile photo grid with hover captions" },
        "FAQ":          { label: "FAQ", blurb: "Accordion of questions with expandable answers" },
        "SERVICE-AREA": { label: "Service area", blurb: "Coverage tags plus credential chips beside them" },
        "LOCATION":     { label: "Find us", blurb: "Address, phone, hours, directions button and dark map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Grid-textured band with headline, contact line and button" },
    },
    "generic:E": {
        "HERO":         { label: "Hero", blurb: "Headline, buttons, photo and two floating info cards" },
        "MARQUEE":      { label: "Scrolling band", blurb: "Scrolling word band under the hero" },
        "TRUST":        { label: "Trust numbers", blurb: "Four rounded colour chips with numbers and labels" },
        "ABOUT":        { label: "Our story", blurb: "Photo with number bubble and story paragraphs" },
        "SERVICES":     { label: "What we do", blurb: "Three cards with icon, bullets and optional badge" },
        "WHY-US":       { label: "Why us", blurb: "Four icon cards giving reasons to choose you" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three circled numbered steps with titles and copy" },
        "TESTIMONIALS": { label: "Happy customers", blurb: "Three quote bubbles with initials and source line" },
        "GALLERY":      { label: "Our work", blurb: "Six-tile photo grid with hover captions" },
        "FAQ":          { label: "Good to know", blurb: "Accordion of questions with expandable answers" },
        "SERVICE-AREA": { label: "Service area", blurb: "Area chips plus credential items beside them" },
        "LOCATION":     { label: "Come by", blurb: "Map, address, phone, hours and directions button" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Rounded blue card with headline, contact line, button" },
    },
    "foodcraft:BL": {
        "HERO":         { label: "Hero", blurb: "Headline, lede, both buttons, tag pills and the arched photo" },
        "TRUST":        { label: "Proof strip", blurb: "Four figures on the espresso band" },
        "ABOUT":        { label: "Our story", blurb: "Photo, story and the two-column spec ledger" },
        "SERVICES":     { label: "The menu", blurb: "Menu cards with tag, detail line and price" },
        "WHY-US":       { label: "Why here", blurb: "Three rust-topped columns of reasons" },
        "GALLERY":      { label: "Gallery", blurb: "Five-tile bento of café photos" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three amber-disc steps on the espresso band" },
        "TESTIMONIALS": { label: "In their words", blurb: "Regulars' quotes, three cards, centred head" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Four cells: how standards are kept" },
        "LOCATION":     { label: "Visit us", blurb: "Map and the opening-hours card" },
        "SERVICE-AREA": { label: "Delivery & catering", blurb: "Areas and delivery times, in a tinted panel" },
        "FAQ":          { label: "Good to know", blurb: "Questions and answers, two columns" },
        "CTA-BAND":     { label: "See you in the morning", blurb: "Espresso half with copy, photo half beside it" },
        "FOOTER":       { label: "Footer", blurb: "Brand, blurb, link columns and the colophon" },
    },
    "foodcraft:BM": {
        "HERO":         { label: "Hero", blurb: "Underlined kicker, headline, lede, two buttons, café photo" },
        "TRUST":        { label: "Proof row", blurb: "Four figures on one ruled row" },
        "ABOUT":        { label: "Our story", blurb: "Room photo, story paragraphs and the six-cell fact table" },
        "SERVICES":     { label: "The menu", blurb: "Menu rows: photo, tag, description and price" },
        "WHY-US":       { label: "Why here", blurb: "Three reasons, numbered I II III" },
        "GALLERY":      { label: "Gallery", blurb: "Five captioned photo tiles" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three steps: order, we start it, collect" },
        "TESTIMONIALS": { label: "From the regulars", blurb: "Three quotes with star ratings and names" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Four numbered promises about beans and standards" },
        "LOCATION":     { label: "Visit us", blurb: "Map, directions line and the opening-hours table" },
        "SERVICE-AREA": { label: "Delivery", blurb: "Areas delivered to, with travel times" },
        "FAQ":          { label: "Good to know", blurb: "Questions and answers, two columns" },
        "CTA-BAND":     { label: "See you soon", blurb: "Dark closing band: copy, button, phone, photo" },
        "FOOTER":       { label: "Footer", blurb: "Brand, blurb, link columns and the colophon" },
    },
    "foodcraft:BN": {
        "HERO":         { label: "Hero", blurb: "Wide roastery photo, kicker, headline, lede, buttons" },
        "TRUST":        { label: "Proof row", blurb: "Four figures across one ruled row" },
        "ABOUT":        { label: "The works", blurb: "Workshop story, photo and the spec ledger" },
        "SERVICES":     { label: "Price list", blurb: "Ruled table: reference, drink, origin, price" },
        "WHY-US":       { label: "Why here", blurb: "Numbered reasons, stacked and ruled" },
        "GALLERY":      { label: "Plates", blurb: "Captioned photo plates of the floor" },
        "HOW-IT-WORKS": { label: "Procedure", blurb: "Three ordering steps on the ink band" },
        "TESTIMONIALS": { label: "On record", blurb: "Numbered regulars' reports with names" },
        "CREDENTIALS":  { label: "Standards", blurb: "Numbered promises: trade, roast dates, training" },
        "LOCATION":     { label: "Location", blurb: "Map, directions line and the opening-hours table" },
        "SERVICE-AREA": { label: "Dispatch", blurb: "Delivery areas and times for beans and batches" },
        "FAQ":          { label: "Notes", blurb: "Numbered questions and answers" },
        "CTA-BAND":     { label: "Contact", blurb: "Rust closing band: copy, button, phone" },
        "FOOTER":       { label: "Footer", blurb: "Brand, blurb, link columns and the colophon" },
    },
    "foodcraft:BO": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, lede, buttons and the drink photo" },
        "TRUST":        { label: "Proof row", blurb: "Four figures in rounded cells" },
        "ABOUT":        { label: "Our story", blurb: "Two photos, the story and the fact cells" },
        "SERVICES":     { label: "The menu", blurb: "Drink cards grouped under flavour headings" },
        "WHY-US":       { label: "Why us", blurb: "Numbered reasons in rounded cards" },
        "GALLERY":      { label: "Gallery", blurb: "Captioned photo tiles from the counter" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three ordering steps, numbered discs" },
        "TESTIMONIALS": { label: "What the suki say", blurb: "Swipeable quote cards with stars and initials" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Numbered promises: permits, training, cleaning" },
        "LOCATION":     { label: "Visit us", blurb: "Map, address and the open-hours card" },
        "SERVICE-AREA": { label: "Delivery", blurb: "Areas delivered to, with travel times" },
        "FAQ":          { label: "Good to know", blurb: "Questions and answers" },
        "CTA-BAND":     { label: "Thirsty yet?", blurb: "Closing panel: copy, button, phone" },
        "FOOTER":       { label: "Footer", blurb: "Brand, blurb, link columns and the colophon" },
    },
    "hospitality:BI": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, two photos, lede, booking buttons" },
        "TRUST":        { label: "Stat rail", blurb: "Big figures and labels — rooms, guests, nights" },
        "SERVICES":     { label: "Stays", blurb: "Room rows with photos, capacity chips and rates" },
        "WHY-US":       { label: "Comforts", blurb: "Amenities grid: pool, aircon, wifi, kitchen, parking" },
        "GALLERY":      { label: "Look around", blurb: "Lead photo plus captioned portrait tiles of property" },
        "ABOUT":        { label: "The place", blurb: "Story paragraphs, pull-quote, owner signature and two photos" },
        "HOW-IT-WORKS": { label: "How it goes", blurb: "Numbered booking steps: message, confirm, arrive" },
        "TESTIMONIALS": { label: "In their words", blurb: "Lead guest quote plus smaller review cards" },
        "FAQ":          { label: "Good to know", blurb: "Accordion house rules and policies, plus phone" },
        "SERVICE-AREA": { label: "Around here", blurb: "List of nearby beaches, cave, airport and pier" },
        "CREDENTIALS":  { label: "On record", blurb: "Label-and-detail rows: accreditations, permits, years hosting" },
        "LOCATION":     { label: "Finding us", blurb: "Address, phone, check-in hours, directions and map" },
        "CTA-BAND":     { label: "Booking band", blurb: "Closing headline, availability button, phone and directions" },
    },
    "hospitality:BK": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo, headline, lede and both buttons" },
        "TRUST":        { label: "Proof strip", blurb: "Four brass figures across one bordered band" },
        "ABOUT":        { label: "The villa", blurb: "Story, the spec ledger and the tall photo" },
        "SERVICES":     { label: "What's included", blurb: "Numbered ledger of inclusions, then the rate panel" },
        "WHY-US":       { label: "Why book direct", blurb: "Three brass-topped columns of reasons" },
        "GALLERY":      { label: "Gallery", blurb: "Five-tile bento of villa photos" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three circled steps on the raised panel" },
        "TESTIMONIALS": { label: "In their words", blurb: "Guest quotes, three cards" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Four cells: what makes the booking safe" },
        "LOCATION":     { label: "Location", blurb: "Map, address and the house-rules table" },
        "SERVICE-AREA": { label: "What's nearby", blurb: "Places and driving times, three columns" },
        "FAQ":          { label: "Good to know", blurb: "Questions and answers, two columns" },
        "CTA-BAND":     { label: "Ready when you are", blurb: "Photo band, closing headline and both buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand, blurb, link columns and the colophon" },
    },
    "hospitality:BJ": {
        "HERO":         { label: "Hero", blurb: "Headline, intro, both buttons and the house photo" },
        "TRUST":        { label: "Proof strip", blurb: "Four figures in one bordered band" },
        "SERVICES":     { label: "The rooms", blurb: "Room cards, rates, and the whole-house band" },
        "WHY-US":       { label: "The house", blurb: "House photo and the two-column amenity list" },
        "GALLERY":      { label: "Photo grid", blurb: "The five-tile bento of house photos" },
        "ABOUT":        { label: "Your host", blurb: "Host copy, portrait, name and contact button" },
        "CREDENTIALS":  { label: "The promises", blurb: "Numbered cards beside the host copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three steps on the green band" },
        "TESTIMONIALS": { label: "In their words", blurb: "Guest quotes, three cards" },
        "SERVICE-AREA": { label: "Nearby", blurb: "What is around the house — not in the original design" },
        "LOCATION":     { label: "Getting here", blurb: "Map, address and the house-rules table" },
        "FAQ":          { label: "Good to know", blurb: "Questions and answers, two columns" },
        "CTA-BAND":     { label: "Ready when you are", blurb: "Green closing slab with both contact buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand, blurb, link columns and contact rows" },
    },
    "medical:AH": {
        "HERO":         { label: "Hero", blurb: "Headline, lede, book and call buttons, two plates" },
        "TRUST":        { label: "Trust strip", blurb: "Hairline-ruled line: years served, licences, rating, hours" },
        "ABOUT":        { label: "About the studio", blurb: "Clinic story paragraphs and the founding dentist's portrait" },
        "SERVICES":     { label: "Care we provide", blurb: "Hairline-ruled treatment cells with descriptions and optional prices" },
        "WHY-US":       { label: "Why patients stay", blurb: "Definition list of reasons beside the quiet headline" },
        "HOW-IT-WORKS": { label: "Your first visit", blurb: "Numbered steps from booking to written plan and aftercare" },
        "TESTIMONIALS": { label: "Patient words", blurb: "Patient quotes on the dark seafoam band" },
        "GALLERY":      { label: "The studio", blurb: "Captioned plates: reception, sterilization room, chairside screen" },
        "FAQ":          { label: "Common questions", blurb: "Accordion of booking, HMO and treatment questions" },
        "SERVICE-AREA": { label: "Patients come from", blurb: "One line of districts patients travel from" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Dot-separated row of licence, association and permit lines" },
        "LOCATION":     { label: "Visit us", blurb: "Address, phone, weekly hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Centred closing headline, a line, one booking button" },
    },
    "medical:AQ": {
        "HERO":         { label: "Hero", blurb: "Headline, lede, buttons, clinic card, credibility rail" },
        "TRUST":        { label: "Trust band", blurb: "Mint band of stat cells: ages, rating, imaging" },
        "ABOUT":        { label: "The clinic", blurb: "Clinic story paragraphs beside a treatment-room photo" },
        "SERVICES":     { label: "Our care", blurb: "Mint band of white icon cards per treatment" },
        "WHY-US":       { label: "Why families choose us", blurb: "Teal-ruled tiles: gentleness, prevention, one family clinic" },
        "HOW-IT-WORKS": { label: "Your first visit", blurb: "Numbered dots: book, exam, clear plan, upkeep" },
        "TESTIMONIALS": { label: "Patient stories", blurb: "Mint quote cards with names, districts and stars" },
        "GALLERY":      { label: "A look around", blurb: "Mosaic of captioned clinic tiles with number chips" },
        "FAQ":          { label: "Good to know", blurb: "Two-column accordion of licensing, nerves and booking questions" },
        "SERVICE-AREA": { label: "Patients come from", blurb: "Tags listing the districts patients travel from" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Badge cards: licence, association, permit, digital imaging" },
        "LOCATION":     { label: "Find the clinic", blurb: "Clinic name, address, phone, hours rows and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Teal band: closing headline, line and booking buttons" },
    },
    "restaurant:AE": {
        "HERO":         { label: "Hero", blurb: "Full-screen grill photo, headline, buttons and specials ticker" },
        "TRUST":        { label: "Trust bar", blurb: "Row of stat cells: years grilling, rating, hours" },
        "ABOUT":        { label: "The story", blurb: "Family history paragraphs and captioned photo plate" },
        "SERVICES":     { label: "Off the grill", blurb: "Card grid of dishes with short descriptions" },
        "WHY-US":       { label: "Why us", blurb: "Ember-ruled list of reasons with short copy" },
        "HOW-IT-WORKS": { label: "Ordering", blurb: "Numbered steps from message to grill to pickup" },
        "TESTIMONIALS": { label: "Word of mouth", blurb: "Customer quote cards with names and barangays" },
        "GALLERY":      { label: "From the grill", blurb: "Photo plates with captions" },
        "FAQ":          { label: "Questions", blurb: "Expandable answers on ordering, parking, catering, reservations" },
        "SERVICE-AREA": { label: "Tray delivery area", blurb: "Dot-separated list of barangays served for trays" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked row of permits and staff certificates" },
        "LOCATION":     { label: "Find the smoke", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Ember band: closing headline and order buttons" },
    },
    "restaurant:AM": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo, headline, three buttons and dish ticker" },
        "TRUST":        { label: "Trust bar", blurb: "Four stat cells: generations, rating, opening time, claim" },
        "ABOUT":        { label: "Our story", blurb: "Drop-cap story paragraphs and captioned kitchen photo" },
        "SERVICES":     { label: "The kitchen", blurb: "Numbered menu rows with tag chips and note" },
        "WHY-US":       { label: "Why us", blurb: "Roman-numbered reason cells with titles and copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps: walk in, reserve, pickup, delivery" },
        "TESTIMONIALS": { label: "In their words", blurb: "Quote cards with customer names and barangays" },
        "GALLERY":      { label: "Room and plates", blurb: "Numbered photo plates with captions" },
        "FAQ":          { label: "Good to know", blurb: "Expandable answers on reservations, pickup, parking, kids" },
        "SERVICE-AREA": { label: "We deliver around", blurb: "Pill tags of barangays served for delivery" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked permit cards with short descriptions" },
        "LOCATION":     { label: "Find us", blurb: "Address, phone, hours rows and map plate" },
        "CTA-BAND":     { label: "Save your table", blurb: "Closing headline with message, call and directions buttons" },
    },
    "restaurant:U": {
        "HERO":         { label: "Hero", blurb: "Locality line, headline, reserve buttons and hero photo" },
        "TRUST":        { label: "Trust bar", blurb: "Olive stat cells: rating, seats, sourcing radius, nights" },
        "ABOUT":        { label: "The house", blurb: "Restaurant story, chef signature and a captioned photo" },
        "SERVICES":     { label: "The carte", blurb: "Roman-numbered courses with descriptions, prices, booking button" },
        "WHY-US":       { label: "Why us", blurb: "Roman-numbered columns: the hearth, the market, the cellar" },
        "HOW-IT-WORKS": { label: "How a night unfolds", blurb: "Numbered steps from booking to the last bite" },
        "MARQUEE":      { label: "Marquee", blurb: "Scrolling italic band of house words" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Centred guest quotes with stars, name and source" },
        "GALLERY":      { label: "A look inside", blurb: "Mosaic of room, fire and plate photos" },
        "FAQ":          { label: "Good to know", blurb: "Accordion of booking, dietary and parking questions" },
        "SERVICE-AREA": { label: "Private dining", blurb: "Neighbourhood chips for private dining and events" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked list of ratings, licences and memberships" },
        "LOCATION":     { label: "Reservations and visit", blurb: "Phone, email, address, hours, map and reserve button" },
        "CTA-BAND":     { label: "Closing band", blurb: "Terracotta band with reserve and call buttons" },
    },
    "restaurant:V": {
        "HERO":         { label: "Hero", blurb: "Eyebrow, centred headline, buttons, stat strip, photo" },
        "TRUST":        { label: "Trust bar", blurb: "Band of big number-and-label stat cells" },
        "ABOUT":        { label: "Our story", blurb: "Story paragraphs, signature and a captioned photo" },
        "SERVICES":     { label: "The card", blurb: "Roman-numbered courses with descriptions, prices, booking button" },
        "WHY-US":       { label: "Why us", blurb: "Roman-numbered columns: fire, market, wine, neighbourhood" },
        "HOW-IT-WORKS": { label: "How a night works", blurb: "Numbered steps from booking to the table" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Centred guest quotes with stars, name and source" },
        "GALLERY":      { label: "The room", blurb: "Grid of room, hearth and plate photos" },
        "FAQ":          { label: "Good to know", blurb: "Accordion of booking, dietary and parking questions" },
        "SERVICE-AREA": { label: "Private dining", blurb: "Neighbourhood chips for private dining and events" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked list of ratings, licences and memberships" },
        "LOCATION":     { label: "Find us", blurb: "Phone, address, weekly hours, map and reserve button" },
        "CTA-BAND":     { label: "Closing band", blurb: "Sage band with reserve and call buttons" },
    },
    "restaurant:W": {
        "HERO":         { label: "Hero", blurb: "Full-screen photo, headline, two buttons and fact strip" },
        "TRUST":        { label: "Trust bar", blurb: "Four stat cells: rating, seats, sourcing radius, nights" },
        "ABOUT":        { label: "The house", blurb: "Story paragraphs, captioned photo and the chef signature" },
        "SERVICES":     { label: "The carte", blurb: "Roman-numbered dish rows with prices, note and reserve button" },
        "WHY-US":       { label: "Why us", blurb: "Roman-numbered columns of house principles with short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered step rows with titles and short copy" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Guest quotes with star ratings and reviewer names" },
        "GALLERY":      { label: "A look inside", blurb: "Photo mosaic tiles with numbers and captions" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on walk-ins, allergies, corkage, parking" },
        "SERVICE-AREA": { label: "Private dining", blurb: "Neighbourhood chips for private dining and events" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked list of licences, ratings and memberships" },
        "LOCATION":     { label: "Visit", blurb: "Phone, address, hours table, reserve button and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Final headline, subline and the reserve/call buttons" },
    },
    "restaurant:X": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo, locality tag, headline and two buttons" },
        "TRUST":        { label: "Trust bar", blurb: "Four stat cells: rating, nights, seats, whole-animal claim" },
        "ABOUT":        { label: "Our story", blurb: "Story paragraphs, captioned chef photo and signature line" },
        "SERVICES":     { label: "The menu", blurb: "Roman-numbered dish rows with prices and booking button" },
        "WHY-US":       { label: "Why us", blurb: "Roman-numbered columns of house principles with short copy" },
        "HOW-IT-WORKS": { label: "How a night works", blurb: "Numbered steps from reserving to the last bite" },
        "TESTIMONIALS": { label: "In their words", blurb: "Guest quotes with star ratings and names" },
        "GALLERY":      { label: "The reel", blurb: "Photo mosaic tiles with numbers and captions" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on walk-ins, allergies, corkage, parking" },
        "SERVICE-AREA": { label: "Private dining", blurb: "Neighbourhood chips for private dining and events" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked list of licences, ratings and memberships" },
        "LOCATION":     { label: "Find us", blurb: "Phone, address, hours table, button and dark map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Final headline with reserve and call buttons" },
    },
    "restaurant:Y": {
        "HERO":         { label: "Hero", blurb: "Stacked photo cards, headline, rating tag and buttons" },
        "TRUST":        { label: "Trust bar", blurb: "Four stat cells: rating, nights, seats, sourcing radius" },
        "ABOUT":        { label: "Our story", blurb: "Story paragraphs, captioned photo and signature line" },
        "SERVICES":     { label: "The menu", blurb: "Bento dish tiles with tags, prices and photo" },
        "WHY-US":       { label: "Why us", blurb: "Roman-numbered columns of reasons with short copy" },
        "HOW-IT-WORKS": { label: "How a night works", blurb: "Numbered steps from reserving to digging in" },
        "TESTIMONIALS": { label: "People are talking", blurb: "Guest quotes with star ratings and names" },
        "GALLERY":      { label: "The reel", blurb: "Photo mosaic tiles with numbers and captions" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on walk-ins, allergies, corkage, parking" },
        "SERVICE-AREA": { label: "Private dining", blurb: "Neighbourhood chips for private dining and events" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked list of licences, permits and memberships" },
        "LOCATION":     { label: "Find us", blurb: "Phone, address, hours table, reserve button and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Final headline with reserve and call buttons" },
    },
    "retail:AG": {
        "HERO":         { label: "Masthead", blurb: "Masthead name, storefront plate, pitch column, two buttons" },
        "TRUST":        { label: "Trust strip", blurb: "Double-ruled line: credibility statement, Google rating, today's hours" },
        "ABOUT":        { label: "The family record", blurb: "Store history paragraphs and two captioned archive photos" },
        "SERVICES":     { label: "Departments & services", blurb: "Rubber-stamp cards for each department and counter service" },
        "WHY-US":       { label: "Why builders come", blurb: "Ink-black band with the ruled list of reasons" },
        "HOW-IT-WORKS": { label: "How to buy", blurb: "Numbered stamp cards: walk in, message list, deliver" },
        "TESTIMONIALS": { label: "From the regulars", blurb: "Red-ruled customer quotes with names and towns" },
        "GALLERY":      { label: "The aisles", blurb: "Captioned sepia photo plates of the store" },
        "FAQ":          { label: "Reader inquiries", blurb: "Accordion of counter questions and answers" },
        "SERVICE-AREA": { label: "Delivery routes", blurb: "One line listing the towns you deliver to" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Diamond-separated row of registration, permit and dealer lines" },
        "LOCATION":     { label: "Find us", blurb: "Address, phone, weekly hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Red band with closing headline and message button" },
    },
    "retail:AO": {
        "HERO":         { label: "Hero", blurb: "Headline, lede, buttons, store photo, meta, department index" },
        "TRUST":        { label: "Trust band", blurb: "Yellow band of ruled stat and rating cells" },
        "ABOUT":        { label: "Our store", blurb: "Store-history paragraphs beside an aisle photo plate" },
        "SERVICES":     { label: "The departments", blurb: "Scrolling department cards plus the counter-services grid" },
        "WHY-US":       { label: "Why buy here", blurb: "Dark ink band of numbered reason tiles" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps from messaging your list to delivery" },
        "TESTIMONIALS": { label: "What builders say", blurb: "Red band of customer quotes with names, towns" },
        "GALLERY":      { label: "Inside the store", blurb: "Mosaic of captioned, numbered store photo tiles" },
        "FAQ":          { label: "Questions", blurb: "Two-column accordion of shop questions and answers" },
        "SERVICE-AREA": { label: "We deliver around", blurb: "Kicker plus stencilled tags of the towns served" },
        "CREDENTIALS":  { label: "Registered & recognised", blurb: "Badge tiles for registration, permit, dealer and association" },
        "LOCATION":     { label: "Find the store", blurb: "Store name, address, phone, hours rows and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Ink band: closing headline, directions, call, message buttons" },
    },
    "salonspa:AN": {
        "HERO":         { label: "Hero", blurb: "Headline, lede, two buttons and the portrait plate" },
        "TRUST":        { label: "Trust strip", blurb: "Dark band of four big figures and labels" },
        "ABOUT":        { label: "The studio", blurb: "Studio photo plate and the about paragraphs" },
        "SERVICES":     { label: "The services", blurb: "Numbered service rows with descriptions and Book links" },
        "WHY-US":       { label: "The difference", blurb: "Grid of reason cells, each a headline and copy" },
        "HOW-IT-WORKS": { label: "Your visit", blurb: "Numbered booking steps from first message to home care" },
        "TESTIMONIALS": { label: "What clients say", blurb: "Client quote cards with names and neighbourhoods" },
        "GALLERY":      { label: "Recent chairs", blurb: "Captioned photo plates in the asymmetric editorial grid" },
        "FAQ":          { label: "Good to know", blurb: "Two columns of expandable question-and-answer rows" },
        "SERVICE-AREA": { label: "Service area", blurb: "Eyebrow over outlined tags of client neighbourhoods" },
        "CREDENTIALS":  { label: "Trained & registered", blurb: "Bordered credential cards with a tick, name and note" },
        "LOCATION":     { label: "Find the studio", blurb: "Studio name, address, phone, hours and the map" },
        "CTA-BAND":     { label: "Book a chair", blurb: "Nude band with closing headline and two buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, visit and link columns, and message pill" },
    },
    "salonspa:K": {
        "HERO":         { label: "Hero", blurb: "Locality line, headline, two buttons, photo with corner tag" },
        "TRUST":        { label: "Trust row", blurb: "Stat figures: rating, private rooms, licensing, hours" },
        "ABOUT":        { label: "The house", blurb: "Story paragraphs, pull-quote and one photo" },
        "SERVICES":     { label: "The menu", blurb: "Service cards with price, description and duration" },
        "WHY-US":       { label: "Why us", blurb: "Numbered reason cells with title and short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps: book, consult, unwind" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Quote cards with guest name and review source" },
        "GALLERY":      { label: "The space", blurb: "Captioned photo tiles of the rooms and work" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on booking, products, parking, cancellation" },
        "SERVICE-AREA": { label: "Who we see", blurb: "Chips listing the neighbourhoods the salon serves" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Licence, massage-therapy, insurance and sanitation badges" },
        "LOCATION":     { label: "Visit", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Dark closing band with headline and two buttons" },
    },
    "salonspa:L": {
        "HERO":         { label: "Hero", blurb: "Headline, intro line, two buttons and a photo band" },
        "TRUST":        { label: "Trust row", blurb: "Stat figures: clean products, private rooms, licensed team" },
        "ABOUT":        { label: "Our story", blurb: "Story paragraphs, pull-quote and one photo" },
        "SERVICES":     { label: "The menu", blurb: "Service cards with price, description and duration" },
        "WHY-US":       { label: "Why us", blurb: "Numbered reason cells with title and short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps: book, consult, unwind" },
        "TESTIMONIALS": { label: "What guests say", blurb: "Quote cards with guest name and review source" },
        "GALLERY":      { label: "The space", blurb: "Captioned photo tiles of the rooms and work" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on booking, products, parking, cancellation" },
        "SERVICE-AREA": { label: "Neighborhoods we welcome", blurb: "Chips listing the neighbourhoods the salon serves" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Licence, massage-therapy, insurance and sanitation badges" },
        "LOCATION":     { label: "Visit", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Dark closing band with headline and two buttons" },
    },
    "salonspa:M": {
        "HERO":         { label: "Hero", blurb: "Headline, intro line, buttons, photo and star rating" },
        "TRUST":        { label: "Trust row", blurb: "Stat figures: rating, rooms, licensing, products, hours" },
        "ABOUT":        { label: "About", blurb: "Story paragraphs, pull-quote and one photo" },
        "SERVICES":     { label: "The menu", blurb: "Service cards with price, description and duration" },
        "WHY-US":       { label: "Why us", blurb: "Numbered reason cells with title and short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps: book, consult, unwind" },
        "TESTIMONIALS": { label: "What guests say", blurb: "Quote cards with guest name and review source" },
        "GALLERY":      { label: "The space", blurb: "Captioned photo tiles of the rooms and work" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on booking, products, parking, cancellation" },
        "SERVICE-AREA": { label: "Neighborhoods we serve", blurb: "Chips listing the neighbourhoods the studio serves" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Licence, massage-therapy, insurance and sanitation badges" },
        "LOCATION":     { label: "Visit", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Dark closing band with headline and two buttons" },
    },
    "salonspa:N": {
        "HERO":         { label: "Hero", blurb: "Eyebrow, oversized headline, intro line, two buttons, photo" },
        "TRUST":        { label: "Trust row", blurb: "Stat figures: rating, rooms, licensing, disciplines" },
        "ABOUT":        { label: "The house", blurb: "Story paragraphs, pull-quote and one photo" },
        "SERVICES":     { label: "The menu", blurb: "Service cards with price, description and duration" },
        "WHY-US":       { label: "Why us", blurb: "Numbered reason cells with title and short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps: book, consult, unwind" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Quote cards with guest name and review source" },
        "GALLERY":      { label: "The showreel", blurb: "Captioned photo tiles of the rooms and work" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on booking, products, parking, cancellation" },
        "SERVICE-AREA": { label: "Who we see", blurb: "Chips listing the neighbourhoods the salon serves" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Licence, massage-therapy, insurance and sanitation badges" },
        "LOCATION":     { label: "Visit", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Dark closing band with headline and two buttons" },
    },
    "salonspa:O": {
        "HERO":         { label: "Hero", blurb: "Headline, intro line, buttons and two stacked photos" },
        "TRUST":        { label: "Trust row", blurb: "Stat figures: rating, rooms, licensing, clean products" },
        "ABOUT":        { label: "Our story", blurb: "Story paragraphs, pull-quote and one photo" },
        "SERVICES":     { label: "The menu", blurb: "Service cards with price, description and duration" },
        "WHY-US":       { label: "Why us", blurb: "Numbered reason cells with title and short copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps: book, consult, unwind" },
        "TESTIMONIALS": { label: "Loved by guests", blurb: "Quote cards with guest name and review source" },
        "GALLERY":      { label: "The space", blurb: "Captioned photo tiles of the rooms and work" },
        "FAQ":          { label: "Good to know", blurb: "Expandable questions on booking, products, parking, cancellation" },
        "SERVICE-AREA": { label: "Neighborhoods we welcome", blurb: "Chips listing the neighbourhoods the salon serves" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Licence, massage-therapy, insurance and sanitation badges" },
        "LOCATION":     { label: "Visit", blurb: "Address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Dark closing band with headline and two buttons" },
    },
    "services:AS": {
        "HERO":         { label: "Hero ticket", blurb: "Ticket headline, checklist lines, buttons and photo plate" },
        "TRUST":        { label: "Trust stats", blurb: "Blue band of stat cells including Google rating" },
        "ABOUT":        { label: "The shop", blurb: "Story paragraphs and the shopfront photo plate" },
        "SERVICES":     { label: "The service menu", blurb: "Service cards with SVC codes and descriptions" },
        "WHY-US":       { label: "Why us", blurb: "Labelled reason cells with headings and copy" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Numbered steps from booking to next-day delivery" },
        "TESTIMONIALS": { label: "Customer receipts", blurb: "Star-rated customer quotes with names and areas" },
        "GALLERY":      { label: "Inside the shop", blurb: "Captioned photo plates in a mosaic grid" },
        "FAQ":          { label: "Questions", blurb: "Expandable answers on pickup, turnaround, tickets, detergents" },
        "SERVICE-AREA": { label: "We pick up around", blurb: "Dashed area tags for the pickup coverage" },
        "CREDENTIALS":  { label: "Registered and careful", blurb: "Badge cards: registration, permit, detergents, care guarantee" },
        "LOCATION":     { label: "Find the shop", blurb: "Shop, address, phone and hours rows plus map" },
        "CTA-BAND":     { label: "Book a pickup", blurb: "Closing headline with message and call buttons" },
        "FOOTER":       { label: "Footer", blurb: "Brand blurb, address, booking links and bottom bar" },
    },
    "shirtstore:AA": {
        "HERO":         { label: "Hero", blurb: "Full-bleed photo, headline, intro, two buttons, rating line" },
        "TRUST":        { label: "Trust stats", blurb: "Four stat cells: customers, rating, cotton, returns" },
        "ABOUT":        { label: "The story", blurb: "Story headline, paragraphs, signature line and the photo" },
        "SERVICES":     { label: "The collection", blurb: "Numbered shirt cards with photo, spec and shop link" },
        "WHY-US":       { label: "Why us", blurb: "Intro, fabric photo and the construction detail items" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three numbered steps from fit quiz to returns" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Rotating customer quotes with name and source" },
        "GALLERY":      { label: "In the wild", blurb: "Captioned photo tiles plus the social tag line" },
        "FAQ":          { label: "Good to know", blurb: "Question and answer accordion rows" },
        "SERVICE-AREA": { label: "Where we serve", blurb: "Shipping note and the neighbourhood name list" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked rows: organic, shipping, sourcing, repairs" },
        "LOCATION":     { label: "Visit the flagship", blurb: "Address, hours, phone, fittings note and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Full-bleed image, closing headline, blurb and buttons" },
    },
    "shirtstore:AB": {
        "HERO":         { label: "Hero", blurb: "Headline, intro, buttons, three-image triptych and the seal" },
        "TRUST":        { label: "Trust stats", blurb: "Four stat cells: customers, rating, cotton, returns" },
        "ABOUT":        { label: "Our story", blurb: "Story headline, paragraphs, signature line and the photo" },
        "SERVICES":     { label: "The collection", blurb: "Numbered shirt cards with photo, spec and shop link" },
        "WHY-US":       { label: "Why us", blurb: "Intro, fabric photo and the construction detail items" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three numbered steps from fit quiz to returns" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Rotating customer quotes with name and source" },
        "GALLERY":      { label: "In the wild", blurb: "Captioned photo tiles plus the social tag line" },
        "FAQ":          { label: "Good to know", blurb: "Question and answer accordion rows" },
        "SERVICE-AREA": { label: "Where we serve", blurb: "Shipping note and the neighbourhood name list" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked rows: organic, shipping, sourcing, repairs" },
        "LOCATION":     { label: "Visit the flagship", blurb: "Address, hours, phone, fittings note and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Full-bleed image, closing headline, blurb and buttons" },
    },
    "shirtstore:AC": {
        "HERO":         { label: "Hero", blurb: "Headline, intro, buttons and the captioned hero photo" },
        "TRUST":        { label: "Trust stats", blurb: "Four stat cells: customers, rating, cotton, returns" },
        "ABOUT":        { label: "Our story", blurb: "Story headline, paragraphs, signature line and the photo" },
        "SERVICES":     { label: "The collection", blurb: "Numbered shirt cards with photo, spec and shop link" },
        "WHY-US":       { label: "Why us", blurb: "Intro, fabric photo and the construction detail items" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three numbered steps from fit quiz to returns" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Rotating customer quotes with name and source" },
        "GALLERY":      { label: "In the wild", blurb: "Captioned photo tiles plus the social tag line" },
        "FAQ":          { label: "Good to know", blurb: "Question and answer accordion rows" },
        "SERVICE-AREA": { label: "Where we serve", blurb: "Shipping note and the neighbourhood name list" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked rows: organic, shipping, sourcing, repairs" },
        "LOCATION":     { label: "Visit the flagship", blurb: "Address, hours, phone, fittings note and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Full-bleed image, closing headline, blurb and buttons" },
    },
    "shirtstore:AD": {
        "HERO":         { label: "Hero", blurb: "Stacked headline, intro, buttons and captioned side photo" },
        "TRUST":        { label: "Trust stats", blurb: "Four stat cells: customers, rating, cotton, returns" },
        "ABOUT":        { label: "The story", blurb: "Story headline, paragraphs, signature line and the photo" },
        "SERVICES":     { label: "The collection", blurb: "Numbered shirt cards with photo, spec and shop link" },
        "WHY-US":       { label: "The difference", blurb: "Intro, fabric photo and the construction detail items" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three numbered steps from fit quiz to returns" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Rotating customer quotes with name and source" },
        "GALLERY":      { label: "Worn everywhere", blurb: "Captioned photo tiles plus the social tag line" },
        "FAQ":          { label: "Good to know", blurb: "Question and answer accordion rows" },
        "SERVICE-AREA": { label: "Where we serve", blurb: "Shipping note and the neighbourhood name list" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked rows: organic, shipping, sourcing, repairs" },
        "LOCATION":     { label: "Visit the flagship", blurb: "Address, hours, phone, fittings note and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Full-bleed image, closing headline, blurb and buttons" },
    },
    "shirtstore:Z": {
        "HERO":         { label: "Hero", blurb: "Kicker, headline, intro, two buttons, wide image band" },
        "TRUST":        { label: "Trust stats", blurb: "Four stat cells: customers, rating, cotton, returns" },
        "ABOUT":        { label: "Our story", blurb: "Story headline, paragraphs, signature line and the photo" },
        "SERVICES":     { label: "The collection", blurb: "Numbered shirt cards with photo, spec and shop link" },
        "WHY-US":       { label: "Why us", blurb: "Intro, fabric photo and the construction detail items" },
        "HOW-IT-WORKS": { label: "How it works", blurb: "Three numbered steps from fit quiz to returns" },
        "TESTIMONIALS": { label: "Reviews", blurb: "Rotating customer quotes with name and source" },
        "GALLERY":      { label: "In the wild", blurb: "Captioned photo tiles plus the social tag line" },
        "FAQ":          { label: "Good to know", blurb: "Question and answer accordion rows" },
        "SERVICE-AREA": { label: "Where we serve", blurb: "Shipping note and the neighbourhood name list" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Ticked rows: organic, shipping, sourcing, repairs" },
        "LOCATION":     { label: "Visit the flagship", blurb: "Address, hours, phone, fittings note and map" },
        "CTA-BAND":     { label: "Closing band", blurb: "Full-bleed image, closing headline, blurb and buttons" },
    },
    "trades:AK": {
        "HERO":         { label: "Hero", blurb: "Sheet-01 headline, intro, call buttons and photo plate" },
        "TRUST":        { label: "Trust strip", blurb: "Strip: years, cities, Google rating, hours, licence" },
        "SERVICE-AREA": { label: "Coverage map", blurb: "Map plate, served-city cells and the coverage note" },
        "ABOUT":        { label: "Company record", blurb: "Company story paragraphs and the crew photo plate" },
        "SERVICES":     { label: "Scope of work", blurb: "Coded service cells, A-01 through E-03" },
        "WHY-US":       { label: "Specification", blurb: "Four numbered clauses: quote, licences, warranty, clean site" },
        "HOW-IT-WORKS": { label: "Procedure", blurb: "Four numbered steps from contact to warranty" },
        "TESTIMONIALS": { label: "Field reports", blurb: "Customer quote cells with names and barangays" },
        "GALLERY":      { label: "Job photos", blurb: "Captioned figure plates of documented, completed jobs" },
        "FAQ":          { label: "Frequently asked", blurb: "Expandable questions on quotes, dispatch, licences, warranty" },
        "CREDENTIALS":  { label: "Credentials", blurb: "Inline row: registration, permit, licence, certifications" },
        "LOCATION":     { label: "Contact block", blurb: "Dispatch address, phone, hours, directions button and map" },
        "CTA-BAND":     { label: "Closing CTA", blurb: "Amber band: headline, sub line and two buttons" },
    },
    "trades:AU": {
        "HERO":         { label: "Hero", blurb: "Headline, tap-to-call number, buttons and coverage ping map" },
        "TRUST":        { label: "Trust row", blurb: "Four cells: licensed, Google rating, cities, insured" },
        "ABOUT":        { label: "Who we are", blurb: "Story paragraphs beside the captioned service-van plate" },
        "SERVICES":     { label: "What we do", blurb: "Six coded service cards, SVC/01 to SVC/06" },
        "WHY-US":       { label: "Why us", blurb: "Four numbered cells: licensed, mobile, quotes, insured" },
        "HOW-IT-WORKS": { label: "Process", blurb: "Four numbered steps from call to finished job" },
        "TESTIMONIALS": { label: "Client logs", blurb: "Star-rated client quotes with names and cities" },
        "GALLERY":      { label: "Work log", blurb: "Six tagged, captioned job plates of finished work" },
        "FAQ":          { label: "Questions", blurb: "Two columns of expandable questions about the service" },
        "SERVICE-AREA": { label: "We cover", blurb: "City chips listing the dispatch coverage area" },
        "CREDENTIALS":  { label: "Licensed and accountable", blurb: "Four badge cards: licences, code, registration, insurance" },
        "LOCATION":     { label: "Dispatch", blurb: "Business rows, no-storefront note and dispatch ping map" },
        "CTA-BAND":     { label: "Call the sparks", blurb: "Closing band: kicker, giant phone number, two buttons" },
    },
    "trades:BQ": {
        "HERO":         { label: "Opening", blurb: "Headline, intro line, two buttons and the angled photo band" },
        "TRUST":        { label: "Proof strip", blurb: "Stone band of short figures with a label under each" },
        "ABOUT":        { label: "The shop", blurb: "Story paragraphs, the shop photo and the spec ledger" },
        "SERVICES":     { label: "Job sheet", blurb: "Ruled table: job, material, finish and lead time" },
        "WHY-US":       { label: "Why us", blurb: "Numbered columns, one reason each" },
        "GALLERY":      { label: "Recent jobs", blurb: "Photo mosaic with a lead tile and captions" },
        "HOW-IT-WORKS": { label: "Process", blurb: "Stone band: numbered steps from enquiry to delivery" },
        "TESTIMONIALS": { label: "Sign-offs", blurb: "Customer quote cards with name and job type" },
        "CREDENTIALS":  { label: "Accountability", blurb: "Ruled row of registrations, licences and cover" },
        "LOCATION":     { label: "The yard", blurb: "Address, phone, hours and the map" },
        "SERVICE-AREA": { label: "Install radius", blurb: "Chips of the places you go, with travel times" },
        "FAQ":          { label: "Asked at the gate", blurb: "Two columns of questions and answers" },
        "CTA-BAND":     { label: "Closing band", blurb: "Angled orange band: headline, one line, two buttons" },
    },
};
